version: '2'
services:
  db:
    image: postgres

  web:
    image: "mingqianye/lense:latest"
    command: bundle exec unicorn -E production -p 8080
    ports:
      - "8080"
    depends_on:
      - migration
      - db
    links:
      - db

  migration:
    image: "mingqianye/lense:latest"
    command: "bundle exec rake db:create db:migrate"
    depends_on:
      - db
    links:
      - db
