default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: lense_development
  username: postgres

test:
  <<: *default
  database: lense_test

production:
  <<: *default
  host: db
  database: lense_production
  username: postgres
  password:
